// modules/module-catalog/src/App.tsx
import { useEffect, useState, useCallback } from 'react';
import type { Vehicle, ModuleContext } from '@platform/contracts';
import { getDataSource, type VehicleFilters } from '@platform/data-source';
import { VehicleFilters as Filters } from './components/VehicleFilters.js';
import { VehicleTable } from './components/VehicleTable.js';
import { VehicleCard } from './components/VehicleCard.js';
import { OrderModal } from './components/OrderModal.js';

interface Props {
  context: ModuleContext;
}

type ViewMode = 'table' | 'detail';

export function App({ context }: Props) {
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [loading, setLoading] = useState(true);
  const [brands, setBrands] = useState<string[]>([]);
  const [selectedVehicle, setSelectedVehicle] = useState<Vehicle | null>(null);
  const [orderVehicle, setOrderVehicle] = useState<Vehicle | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('table');

  const tradeInEnabled = context.featureFlags.trade_in_enabled ?? false;
  const networkMode = context.featureFlags.network_mode ?? false;

  const loadVehicles = useCallback(async (filters?: VehicleFilters) => {
    setLoading(true);
    try {
      const ds = await getDataSource();
      const appliedFilters: VehicleFilters = {
        ...filters,
        // Без "Вся сеть" — показываем только dealer-1 (текущий дилер)
        ...(!networkMode && !filters?.dealerId ? { dealerId: 'dealer-1' } : {}),
      };
      const data = await ds.vehicles.getAll(appliedFilters);
      setVehicles(data);

      if (brands.length === 0) {
        const uniqueBrands = [...new Set(data.map((v) => v.brand))].sort();
        setBrands(uniqueBrands);
      }
    } catch (err) {
      console.error('[Catalog] Failed to load vehicles:', err);
      context.eventBus.publish({
        version: 1,
        type: 'Notification',
        level: 'error',
        message: 'Не удалось загрузить каталог',
      });
    } finally {
      setLoading(false);
    }
  }, [context.eventBus, brands.length, networkMode]);

  useEffect(() => {
    loadVehicles();
  }, [loadVehicles]);

  const handleSelect = (vehicle: Vehicle) => {
    setSelectedVehicle(vehicle);
    setViewMode('detail');

    context.eventBus.publish({
      version: 2,
      type: 'VehicleSelected',
      vehicleId: vehicle.id,
      brand: vehicle.brand,
      model: vehicle.model,
      price: vehicle.price,
      year: vehicle.year,
    });
  };

  const handleOpenOrderModal = (vehicle: Vehicle) => {
    setOrderVehicle(vehicle);
  };

  const handleCreateOrder = async (data: { customerName: string; customerPhone: string; comment: string }) => {
    if (!orderVehicle) return;

    try {
      const ds = await getDataSource();
      const order = await ds.orders.create({
        vehicleId: orderVehicle.id,
        customerName: data.customerName,
        customerPhone: data.customerPhone || undefined,
        comment: data.comment || undefined,
        totalPrice: orderVehicle.price,
      });

      context.eventBus.publish({
        version: 1,
        type: 'OrderCreated',
        orderId: order.id,
        vehicleId: orderVehicle.id,
        customerName: order.customerName,
        totalPrice: order.totalPrice,
        createdAt: order.createdAt,
      });

      context.eventBus.publish({
        version: 1,
        type: 'Notification',
        level: 'success',
        message: `Заказ ${order.id} создан: ${orderVehicle.brand} ${orderVehicle.model}`,
      });

      setOrderVehicle(null);
      setSelectedVehicle(null);
      setViewMode('table');
      await loadVehicles();
    } catch (err) {
      console.error('[Catalog] Failed to create order:', err);
      context.eventBus.publish({
        version: 1,
        type: 'Notification',
        level: 'error',
        message: 'Не удалось создать заказ',
      });
    }
  };

  return (
    <div className="flex-col gap-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <h2>{context.t('catalog.title')}</h2>
          <span className={`badge ${networkMode ? 'badge-info' : 'badge-neutral'}`}>
            {networkMode ? 'Вся сеть' : 'Дилер 1'}
          </span>
          {viewMode === 'detail' && (
            <button
              className="btn btn-ghost btn-sm"
              onClick={() => { setViewMode('table'); setSelectedVehicle(null); }}
            >
              ← К списку
            </button>
          )}
        </div>
        <span className="text-sm text-muted">{vehicles.length} автомобилей</span>
      </div>

      {viewMode === 'table' && (
        <>
          <Filters onFilter={loadVehicles} brands={brands} />

          {loading ? (
            <div className="module-loading">{context.t('common.loading')}</div>
          ) : (
            <VehicleTable
              vehicles={vehicles}
              onSelect={handleSelect}
              onCreateOrder={handleOpenOrderModal}
              tradeInEnabled={tradeInEnabled}
              networkMode={networkMode}
            />
          )}
        </>
      )}

      {viewMode === 'detail' && selectedVehicle && (
        <VehicleCard
          vehicle={selectedVehicle}
          onClose={() => { setViewMode('table'); setSelectedVehicle(null); }}
          onCreateOrder={handleOpenOrderModal}
          tradeInEnabled={tradeInEnabled}
        />
      )}

      {orderVehicle && (
        <OrderModal
          vehicle={orderVehicle}
          onSubmit={handleCreateOrder}
          onClose={() => setOrderVehicle(null)}
        />
      )}
    </div>
  );
}

// modules/module-dashboard/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import type { ModuleContext, DashboardStats, VehicleSelected } from '@platform/contracts';
import { isMinVersion } from '@platform/contracts';
import { getDataSource } from '@platform/data-source';
import StatCards from './components/StatCards.vue';
import RecentOrders from './components/RecentOrders.vue';
import TopBrands from './components/TopBrands.vue';
import SelectedVehicle from './components/SelectedVehicle.vue';
import SalesFunnel from './components/SalesFunnel.vue';

const props = defineProps<{ context: ModuleContext }>();

const stats = ref<DashboardStats | null>(null);
const loading = ref(true);
const networkMode = ref(props.context.featureFlags.network_mode ?? false);
const selectedVehicle = ref<{ brand: string; model: string; price: number; year: number; vehicleId: string } | null>(null);

let unsubOrderCreated: (() => void) | null = null;
let unsubVehicleSelected: (() => void) | null = null;
let unsubDashboardRefresh: (() => void) | null = null;

async function loadStats() {
  loading.value = true;
  try {
    const ds = await getDataSource();
    stats.value = await ds.dashboard.getStats();
  } catch (err) {
    console.error('[Dashboard] Failed to load stats:', err);
    props.context.eventBus.publish({
      version: 1,
      type: 'Notification',
      level: 'error',
      message: 'Не удалось загрузить дашборд',
    });
  } finally {
    loading.value = false;
  }
}

onMounted(() => {
  loadStats();

  // Cross-module: order created in catalog → refresh dashboard
  unsubOrderCreated = props.context.eventBus.subscribe('OrderCreated', (event) => {
    props.context.eventBus.publish({
      version: 1,
      type: 'Notification',
      level: 'info',
      message: `Новый заказ ${event.orderId} — обновляем дашборд`,
    });
    loadStats();
  });

  // Cross-module: vehicle selected in catalog → show in dashboard
  unsubVehicleSelected = props.context.eventBus.subscribe('VehicleSelected', (event: VehicleSelected) => {
    if (isMinVersion(event, 2) && 'price' in event) {
      // v2 event has price and year
      selectedVehicle.value = {
        brand: event.brand,
        model: event.model,
        price: event.price,
        year: event.year,
        vehicleId: event.vehicleId,
      };
    } else {
      // v1 fallback — no price/year
      selectedVehicle.value = {
        brand: event.brand,
        model: event.model,
        price: 0,
        year: 0,
        vehicleId: event.vehicleId,
      };
    }
  });

  // Cross-module: orders module requests dashboard refresh after status change
  unsubDashboardRefresh = props.context.eventBus.subscribe('DashboardRefreshRequested', () => {
    loadStats();
  });
});

onUnmounted(() => {
  unsubOrderCreated?.();
  unsubVehicleSelected?.();
  unsubDashboardRefresh?.();
});
</script>

<template>
  <div class="flex-col gap-4">
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-3">
        <h2>{{ context.t('dashboard.title') }}</h2>
        <span :class="['badge', networkMode ? 'badge-info' : 'badge-neutral']">
          {{ networkMode ? 'Вся сеть' : 'Дилер 1' }}
        </span>
      </div>
      <button class="btn btn-secondary btn-sm" @click="loadStats">
        ↻ Обновить
      </button>
    </div>

    <div v-if="loading" class="module-loading">
      {{ context.t('common.loading') }}
    </div>

    <template v-else-if="stats">
      <StatCards :stats="stats" :network-mode="networkMode" />

      <div class="grid grid-cols-3 gap-4">
        <div style="grid-column: span 2">
          <div class="flex-col gap-4">
            <RecentOrders :orders="stats.recentOrders" />
            <SalesFunnel :stats="stats" />
          </div>
        </div>
        <div class="flex-col gap-4">
          <TopBrands :brands="stats.topBrands" />
          <SelectedVehicle :vehicle="selectedVehicle" />
        </div>
      </div>
    </template>
  </div>
</template>
